name: Doctest build

on: 
  push:
    paths-ignore:
      - 'locale/**'

  pull_request:
    paths-ignore:
      - 'locale/**'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  doctest:

    runs-on: ubuntu-latest
    name: Doctest

    services:
      image: docker

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        fetch-depth: 1
    - name: Set up Python 3.9
      uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b # v4.6.0
      with:
        python-version: 3.9
    - name: Pip upgrade
      run: |
          python -m pip install --upgrade pip
    - name: Build test code
      run: |
          make -f docker.mk doctest
    - name: Upload build artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: Doctest build
        path: ./build/doctest/output.txt
