name: Doctest build

on: 
  push:
    paths-ignore:
      - 'locale/**'

  pull_request:
    paths-ignore:
      - 'locale/**'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  doctest:

    runs-on: ubuntu-latest
    name: Doctest

    services:
      image: docker

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 1
    - name: Set up Python 3.9
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: 3.9
    - name: Pip upgrade
      run: |
          python -m pip install --upgrade pip
    - name: Build test code
      run: |
          make -f docker.mk doctest
    - name: Upload build artifact
      uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4.0.0
      with:
        name: Doctest build
        path: ./build/doctest/output.txt
