name: Update English PO files for translation

on:
  push:
    branches:
      - release_3.40
    paths:
      - 'docs/**'
      - 'themes/**/*.html'

  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  prepare_translation:

    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    if: github.repository_owner == 'qgis'
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          files.pythonhosted.org:443
          github.com:443
          pypi.org:443
          qgis.org:443

    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: release_3.40

    - name: Set up Python 3.12
      uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-intl sphinxext.rediraffe pyYAML sphinx_togglebutton sphinx_copybutton

    - name: Generate English PO files
      id: "generate-po-files"
      run: |
          make gettext
          sphinx-intl update -p build/gettext -l en
          # Remove obsolete strings from the generated *.po files
          find locale/en/LC_MESSAGES/ -type f -name '*.po' -exec sed -i '/^#~ /,/^$/d' {} \;

    - name: Commit the changes in the PO files      
      id: "auto-commit-action"
      uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
      with:
        commit_message: Update English PO files

    - name: "Inform that changes have been made"
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      run: echo "Changes committed!"

    - name: "Inform that no changes were performed"
      if: steps.auto-commit-action.outputs.changes_detected == 'false'
      run: echo "No Changes detected!"
